# Generated by Django 4.2.2 on 2023-09-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='currentFollow',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
